spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linkforge_dev
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    username: dev@example.com
    password: dev_password
  flyway:
    clean-disabled: false

application:
  jwt:
    secret: devSecretKey32CharactersMinimumForHS256AlgorithmSecurity1234567
  base-url: http://localhost:8080
  frontend-url: http://localhost:3000
  safe-browsing:
    enabled: false

logging:
  level:
    com.linkforge: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    include-message: always
    include-stacktrace: on_trace_param
